#!/bin/bash
# Lightweight /healthz probe for Docker HEALTHCHECK and the watchdog.
#
# Exit status is intentionally richer than a normal health check:
#   0  healthy end-to-end (Apache -> Plack -> Koha -> database)
#   1  HTTP/proxy/Plack failure; restarting Plack may help
#   2  /healthz reached Plack, but Koha reports the database unhealthy
#
# Docker treats either non-zero status as unhealthy. The watchdog uses status 2
# to avoid repeatedly restarting a healthy Plack process when MariaDB is down.

set -u

port="${1:?usage: healthz-probe.sh PORT}"
timeout="${HEALTHCHECK_TIMEOUT:-${WATCHDOG_HTTP_TIMEOUT:-10}}"

OPACPORT="${OPACPORT:-80}"
INTRAPORT="${INTRAPORT:-8080}"
LIBRARY_NAME="${LIBRARY_NAME:-defaultlibraryname}"
DOMAIN="${DOMAIN:-}"
OPACPREFIX="${OPACPREFIX:-}"
OPACSUFFIX="${OPACSUFFIX:-}"
INTRAPREFIX="${INTRAPREFIX:-}"
INTRASUFFIX="${INTRASUFFIX:-}"

if [ -n "$DOMAIN" ]; then
    if [ "$port" = "$OPACPORT" ]; then
        host="${OPACPREFIX}${OPACSUFFIX}${DOMAIN}"
    elif [ "$port" = "$INTRAPORT" ]; then
        host="${INTRAPREFIX}${INTRASUFFIX}${DOMAIN}"
    else
        echo "Unknown Koha HTTP port: $port" >&2
        exit 1
    fi
else
    host="$LIBRARY_NAME"
fi

body_file=$(mktemp)
trap 'rm -f "$body_file"' EXIT

if ! code=$(curl \
    --silent \
    --show-error \
    --output "$body_file" \
    --write-out '%{http_code}' \
    --max-time "$timeout" \
    --resolve "${host}:${port}:127.0.0.1" \
    "http://${host}:${port}/healthz" \
    2>/dev/null); then
    exit 1
fi

body=$(cat "$body_file")

if [ "$code" = 200 ] && [ "$body" = "ok" ]; then
    exit 0
fi

# This exact response is generated by plack-health.psgi when the request reached
# a live Koha worker but its SELECT 1 database check failed.
if [ "$code" = 503 ] && [ "$body" = "unhealthy" ]; then
    exit 2
fi

# Anything else (including Apache-generated 502/503 responses) means the
# application path itself is broken rather than a known database-only failure.
exit 1
